name:                prob-den
version:             0.1.0.0
author:              "Joe Qian"
maintainer:          "qzy@g.ucla.edu"
description:         Exploration of denotation of probabilistic programs
ghc-options:         -Wall

dependencies:
- base
- mwc-random
- mtl
- groom
- transformers
- errors
- containers

library:
  source-dirs: src
