name:                prob-den
version:             0.1.0.0
author:              "Joe Qian"
maintainer:          "qzy@g.ucla.edu"
description:         Exploration of denotation of probabilistic programs
ghc-options:         -Wall -O2

dependencies:
- base
- mwc-random
- mtl
- transformers
- containers >= 0.5.11
- array
- reflection
- megaparsec
- text

library:
  source-dirs: src

executables:
  prob:
    main: Main.hs
    source-dirs: main
    dependencies:
      - base
      - optparse-applicative
      - prob-den
